title = "Sci-fi Books Club"
baseURL = "https://scifibooks.club/"
languageCode = "en-us"
theme = "ananke"
# themesDir = "../.."
# resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 9
googleAnalytics = ""
enableRobotsTXT = true
disqusShortname = "scifibooks-club"

[languages]
  [languages.en]
    title = "Sci-fi Books Club"
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/favicon.ico"
  site_logo = "/images/icon2.png"
  description = "Reading the Star Trek relaunch books (post Nemesis) in sensible order."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/bg1.jpg"
  recent_posts_number = 4
  custom_js = ["js/script.js"]
  custom_css = ["css/styles.css"]
  recent_copy = "Latest reviews"
  env = "production"
  # Images can be used in twitter cards etc.
  images = ["/images/social_media_card.jpg"]

[taxonomyPageList]
  other = "Results for “{{ .Title }}”"

[menu]
  [[menu.top]]
    identifier = "reviews"
    name = "Reviews"
    URL = '/reviews'
    weight = 1
  [[menu.top]]
    identifier = "about"
    name = "About"
    URL = '/about'
    weight = 3
  [[menu.top]]
    identifier = 'blog'
    name = "Blog"
    URL = '/blog'
    weight = 3
  [[menu.top]]
    identifier = 'contact'
    name = "Contact"
    URL = '/contact'
    weight = 5
    
[taxonomies]
   tag = "tags"
   series = "series"
