backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/uploads" # Media files will be stored in the repo under static/uploads
public_folder: "/uploads" # The src attribute for uploaded media will begin with /uploads

site_url: https://scifibooks.club

collections:
  - name: "review"
    label: "Review"
    folder: "content/en/reviews"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Book author", name: "book_author", widget: "string" }
      - { label: "Book title", name: "book_title", widget: "string" }
      - { label: "Date", name: "date", widget: "date" }
      - { label: "Description", name: "description", widget: "string"}
      - { label: "Weight", name: "weight", widget: "number"}
      - { label: "Inline image", name: "inline_image", widget: "string"}
      - { label: "Rating", name: "rating", widget: "number"}
      - { label: "Series", name: "series", widget: "list"}
      - { label: "Tags", name: "tags", widget: "list", summary: "{{fields.tag}}", fields: { label: "Tag", name: "tag", widget: "string" }}
      - { label: "Show reading time", name: "show_reading_time", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }
