---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 
sections:
- type: directory
  path: content/en/about
  label: About
  create: all
  match: "**/*"
- type: document
  path: content/en/_index.md
  label: Home
- type: document
  path: config.toml
  label: Site Settings
- type: directory
  path: content/en/reviews
  label: Reviews
  create: all
  match: "**/*"
  templates:
  - review
- type: directory
  path: content/en/blog
  label: Blog
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.81.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.81.0
